<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FinvizLink</AssemblyName>
    <RootNamespace>FinvizLink</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TradingPlatform.BusinessLayer">
      <HintPath>D:\Quantower _ LATEST\Quantower\TradingPlatform\v1.146.10\bin\TradingPlatform.BusinessLayer.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TradingPlatform.PresentationLayer.Plugins">
      <HintPath>D:\Quantower _ LATEST\Quantower\TradingPlatform\v1.146.10\bin\TradingPlatform.PresentationLayer.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TradingPlatform.RTD">
      <HintPath>D:\Quantower _ LATEST\Quantower\TradingPlatform\v1.146.10\bin\TradingPlatform.RTD.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
